// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.sven.tio.common.proto;

public interface CommonProtocolOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommonProtocol)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.CommonProtocol.CommonHeader CommHeader = 1;</code>
   * @return Whether the commHeader field is set.
   */
  boolean hasCommHeader();
  /**
   * <code>.CommonProtocol.CommonHeader CommHeader = 1;</code>
   * @return The commHeader.
   */
  com.sven.tio.common.proto.CommonProtocol.CommonHeader getCommHeader();
  /**
   * <code>.CommonProtocol.CommonHeader CommHeader = 1;</code>
   */
  com.sven.tio.common.proto.CommonProtocol.CommonHeaderOrBuilder getCommHeaderOrBuilder();

  /**
   * <code>.CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
   * @return Whether the liveHeader field is set.
   */
  boolean hasLiveHeader();
  /**
   * <code>.CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
   * @return The liveHeader.
   */
  com.sven.tio.common.proto.CommonProtocol.LiveCommonHeader getLiveHeader();
  /**
   * <code>.CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
   */
  com.sven.tio.common.proto.CommonProtocol.LiveCommonHeaderOrBuilder getLiveHeaderOrBuilder();

  /**
   * <code>bytes Data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
