// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.sven.tio.common.proto;

public interface FrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Frame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageType = 2;</code>
   * @return The messageType.
   */
  java.lang.String getMessageType();
  /**
   * <code>string messageType = 2;</code>
   * @return The bytes for messageType.
   */
  com.google.protobuf.ByteString
      getMessageTypeBytes();

  /**
   * <code>bytes payload = 15;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
