// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.sven.tio.common.proto;

public interface RegisterRoutMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegisterRoutMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 serverId = 1;</code>
   * @return The serverId.
   */
  int getServerId();
}
