// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.sven.tio.common.proto;

public interface ServerBusyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServerBusyMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
